// Run against tests/preview_web.py: isolated temporary router and mocked commands.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert=require('node:assert/strict');
const path=require('node:path');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH || undefined});
 try{
 const page=await browser.newPage({viewport:{width:1440,height:1100},colorScheme:'light'}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8879');
 await page.getByRole('heading',{name:'YouTube',exact:true}).waitFor();
 let bot={token_set:false,ids:[],running:false};
 await page.route('**/api/bot',async route=>{
   if(route.request().method()==='POST'){
     const payload=route.request().postDataJSON();
     if(payload.action==='token')bot.token_set=true;
     if(payload.action==='ids')bot.ids=payload.ids.trim().split(/\s+/);
     if(payload.action==='start')bot.running=true;
     if(payload.action==='stop')bot.running=false;
   }
   await route.fulfill({contentType:'application/json',body:JSON.stringify(bot)});
 });
 await page.reload();
 await page.locator('#botToken').fill('123456789:AAFAKE_SECRET_12345678901234567890');
 await page.locator('#botSaveToken').click();
 await page.locator('#botTokenStatus').getByText('Токен задан').waitFor();
 assert.equal(await page.locator('#botToken').inputValue(),'','token field is cleared after save');
 await page.locator('#botIds').fill('123456789\n987654321');
 await page.locator('#botSaveIds').click();
 await page.locator('#botToggle').getByText('Включить бота').waitFor();
 await page.locator('#botToggle').click();
 await page.locator('#botRunning').getByText('Работает').waitFor();
 await page.unroute('**/api/bot');
 await page.reload();
 await page.getByRole('heading',{name:'YouTube',exact:true}).waitFor();
 const out=path.resolve(__dirname,'../docs');
 await page.screenshot({path:out+'/ui-light.png',fullPage:true,animations:'disabled'});
 await page.emulateMedia({colorScheme:'dark'});
 await page.screenshot({path:out+'/ui-dark.png',fullPage:true,animations:'disabled'});
 await page.setViewportSize({width:390,height:844});
 const smallControls=await page.locator('input:not([type=file]),textarea,select').evaluateAll(nodes=>nodes.filter(node=>getComputedStyle(node).fontSize).map(node=>({id:node.id||node.className,size:parseFloat(getComputedStyle(node).fontSize)})));
 assert.equal(smallControls.filter(control=>control.size<16).length,0,'mobile text controls must not trigger iOS focus zoom: '+JSON.stringify(smallControls.filter(control=>control.size<16)));
 await page.screenshot({path:out+'/ui-mobile.png',fullPage:true,animations:'disabled'});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'mobile horizontal overflow');
 await page.route('**/cgi-bin/state.sh',route=>route.fulfill({status:503,contentType:'application/json',body:'{"error":"temporary"}'}));
 await page.reload();
 await page.locator('#devicePreview').getByText(/Без Pivas: нет устройств/).waitFor();
 await page.unroute('**/cgi-bin/state.sh');
 await page.route('**/api/devices',route=>route.fulfill({status:503,contentType:'application/json',body:'{"error":"Устройства временно недоступны"}'}));
 await page.reload();
 await page.locator('#deviceDisclosureCount').getByText('Ошибка загрузки').waitFor();
 await page.locator('#deviceError').getByText(/Устройства временно недоступны/).waitFor();
 await page.unroute('**/api/devices');
 await page.reload();
 await page.getByRole('heading',{name:'YouTube',exact:true}).waitFor();
 await page.locator('#deviceDisclosureCount').getByText(/устройств/).waitFor();
 await page.locator('#devices').screenshot({path:out+'/ui-devices-mobile.png',animations:'disabled'});
 assert.equal(await page.locator('#deviceDisclosure').evaluate(e=>e.open),false,'device list starts collapsed');
 assert.equal(await page.locator('.device-row').first().isVisible(),false,'device rows stay hidden until expanded');
 await page.locator('#deviceDisclosure > summary').click();
 await page.locator('.device-row').first().waitFor({state:'visible'});
 await page.locator('#devices').screenshot({path:out+'/ui-devices-mobile-expanded.png',animations:'disabled'});
 const deviceRow=()=>page.locator('.device-row').filter({hasText:'MacBook'});
 const deviceRead=()=>page.request.get('http://127.0.0.1:8879/api/devices').then(r=>r.json());
 await deviceRow().getByRole('button',{name:'Без Pivas для MacBook',exact:true}).click();
 await page.locator('#confirmOk').click();
 await deviceRow().getByRole('button',{name:'Включить Pivas для MacBook',exact:true}).waitFor();
 let deviceData=await deviceRead();assert.equal(deviceData.devices.find(d=>d.name==='MacBook').excluded,true);
 assert.equal(deviceData.devices.find(d=>d.name==='Phone').excluded,false);
 await page.locator('#refreshDevices').click();
 await deviceRow().getByRole('button',{name:'Включить Pivas для MacBook',exact:true}).waitFor();
 await page.locator('#deviceDisclosure > summary').click();
 assert.equal(await deviceRow().isVisible(),false,'device list can be collapsed again');
 await page.locator('#devicePreview').click();
 await deviceRow().waitFor({state:'visible'});
 await page.setViewportSize({width:1440,height:1100});
 await page.locator('#toast').waitFor({state:'hidden'});
 await page.locator('#devices').screenshot({path:out+'/ui-devices.png',animations:'disabled'});
 await page.setViewportSize({width:390,height:844});
 await page.locator('#deviceSearch').fill('192.168.1.10');assert.equal(await page.locator('.device-row').count(),1);
 await page.locator('#deviceSearch').fill('');
 await deviceRow().getByRole('button',{name:'Включить Pivas для MacBook',exact:true}).click();await page.locator('#confirmOk').click();
 await deviceRow().getByRole('button',{name:'Без Pivas для MacBook',exact:true}).waitFor();
 assert.equal((await deviceRead()).devices.find(d=>d.name==='MacBook').excluded,false);
 await page.route('**/api/devices',async route=>{
   if(route.request().method()==='POST')return route.fulfill({status:409,contentType:'application/json',body:JSON.stringify({error:'Исключения изменились. Обновите список устройств'})});
   return route.continue();
 });
 await deviceRow().getByRole('button',{name:'Без Pivas для MacBook',exact:true}).click();await page.locator('#confirmOk').click();
 await page.locator('#deviceError').getByText(/Исключения изменились/).waitFor();
 assert.equal((await deviceRead()).devices.find(d=>d.name==='MacBook').excluded,false);
 await page.unroute('**/api/devices');await page.locator('#refreshDevices').click();
 await page.locator('#deviceError').waitFor({state:'hidden'});
 const catalogBeforeSwap=await page.request.get('http://127.0.0.1:8879/api/catalog').then(r=>r.json());
 const server1=await page.locator('#server1').innerText(),server2=await page.locator('#server2').innerText();
 await page.getByRole('button',{name:'⇄ Поменять ссылки',exact:true}).click();
 await page.waitForFunction(expected=>document.getElementById('server1').textContent===expected,server2);
 assert.equal(await page.locator('#server2').innerText(),server1);
 assert.equal(await page.locator('#confirm').isVisible(),false,'swap must be a single click');
 assert.deepEqual(await page.request.get('http://127.0.0.1:8879/api/catalog').then(r=>r.json()),catalogBeforeSwap);
 await page.getByRole('button',{name:'⇄ Поменять ссылки',exact:true}).click();
 await page.waitForFunction(expected=>document.getElementById('server1').textContent===expected,server1);
 assert.equal(await page.locator('#server2').innerText(),server2);
 await page.route('**/api/control',route=>route.fulfill({status:409,contentType:'application/json',body:JSON.stringify({error:'Команда не выполнена. Проверьте конфигурацию и диагностический отчёт'})}));
 await page.getByRole('button',{name:'⇄ Поменять ссылки',exact:true}).click();
 await page.locator('#error').getByText(/Команда не выполнена/).waitFor();
 assert.equal(await page.locator('#server1').innerText(),server1);
 await page.unroute('**/api/control');await page.locator('#refresh').click();await page.locator('#error').waitFor({state:'hidden'});
 const mirrorState=await page.request.get('http://127.0.0.1:8879/cgi-bin/state.sh').then(r=>r.json());
 mirrorState.slot2={...mirrorState.slot1,same_as_slot1:true};
 await page.route('**/cgi-bin/state.sh',route=>route.fulfill({contentType:'application/json',body:JSON.stringify(mirrorState)}));
 await page.locator('#refresh').click();
 await page.locator('#server2').getByText('Ссылка слота 1',{exact:true}).waitFor();
 assert.equal(await page.locator('#slot2Mirror').isVisible(),true);
 assert.equal(await page.locator('#swapSlots').isDisabled(),true);
 await page.unroute('**/cgi-bin/state.sh');await page.locator('#refresh').click();
 await page.locator('#server2').getByText(server2,{exact:true}).waitFor();
 assert.equal(await page.locator('#slot2Mirror').isVisible(),false);
 await page.waitForFunction(()=>!document.querySelector('#swapSlots').disabled);
 await page.locator('#routeDomain').fill('youtube.com');await page.locator('#routeForm').getByRole('button').click();
 await page.locator('#routeResult').getByText('youtube.com → Слот 1',{exact:true}).waitFor();
 await page.locator('#measureIdle').click();await page.locator('#performanceResult').getByRole('heading',{name:'В покое',exact:true}).waitFor();
 await page.locator('#measureLoad').click();await page.locator('#performanceResult').getByRole('heading',{name:'Под нагрузкой',exact:true}).waitFor();
 await page.locator('#backupPassword').fill('browser backup password');
 const [backupDownload]=await Promise.all([page.waitForEvent('download'),page.locator('#backupExport').click()]);
 assert.equal(backupDownload.suggestedFilename(),'pivas-backup.pivas');
 const beforeBackup=await page.request.get('http://127.0.0.1:8879/api/catalog').then(r=>r.json());
 const extra=await page.request.post('http://127.0.0.1:8879/api/catalog',{data:{revision:beforeBackup.revision,action:'domain-add',domains:['after-backup.example'],slot:1}});assert.equal(extra.status(),200);
 await page.locator('#backupFile').setInputFiles(await backupDownload.path());await page.locator('#backupPassword').fill('wrong backup password');await page.locator('#backupCheck').click();
 await page.locator('#backupError').getByText(/Операция не выполнена/).waitFor();assert.equal(await page.locator('#backupRestore').isVisible(),false);
 await page.locator('#backupPassword').fill('browser backup password');await page.locator('#backupCheck').click();await page.locator('#backupRestore').waitFor();
 await page.locator('#backupRestore').click();await page.locator('#confirmOk').click();await page.locator('#backupRestore').waitFor({state:'hidden'});
 const afterRestore=await page.request.get('http://127.0.0.1:8879/api/catalog').then(r=>r.json());assert.deepEqual(afterRestore.groups,beforeBackup.groups);assert.deepEqual(afterRestore.standalone,beforeBackup.standalone);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'new tools mobile overflow');
 await page.getByRole('button',{name:'+ Создать группу',exact:true}).click();
 await page.getByLabel('Название группы',{exact:true}).fill('Тестовая группа');
 await page.locator('#editDomains').fill(Array.from({length:8},(_,i)=>'d'+i+'.example.test').join('\n'));
 await page.locator('#editForm').getByRole('button',{name:'Сохранить',exact:true}).click();
 const card=()=>page.locator('.group-card').filter({has:page.getByRole('heading',{name:'Тестовая группа',exact:true})});
 await card().waitFor();assert.match(await card().innerText(),/8 записей/);
 await card().getByRole('combobox').selectOption('2');
 await page.waitForFunction(()=>[...document.querySelectorAll('.group-card')].some(x=>x.textContent.includes('Тестовая группа')&&x.dataset.slot==='2'));
 const read=()=>page.request.get('http://127.0.0.1:8879/api/catalog').then(r=>r.json());
 assert.equal((await read()).groups.find(g=>g.name==='Тестовая группа').slot,2);
 await card().getByRole('button',{name:'Приостановить группу',exact:true}).click();
 await card().getByRole('button',{name:'Включить группу',exact:true}).waitFor();
 assert.equal((await read()).groups.find(g=>g.name==='Тестовая группа').enabled,false);
 await card().getByRole('button',{name:'Включить группу',exact:true}).click();
 await card().getByRole('button',{name:'Приостановить группу',exact:true}).waitFor();
 await card().getByRole('button',{name:'Изменить группу Тестовая группа',exact:true}).click();
 await page.locator('#editDomains').fill('edited.example.test');
 await page.locator('#editForm').getByRole('button',{name:'Сохранить',exact:true}).click();
 await card().getByText('edited.example.test',{exact:true}).waitFor();
 await page.locator('#search').fill('edited.example.test');assert.equal(await page.locator('.group-card').count(),1);
 await page.locator('#search').fill('');
 await card().getByRole('button',{name:'Удалить',exact:true}).click();
 await page.locator('#confirmOk').click();
 await card().waitFor({state:'detached'});
 await page.getByRole('button',{name:'+ Домен',exact:true}).click();
 await page.locator('#editDomains').fill('solo.example.test');
 await page.locator('#editForm').getByRole('button',{name:'Сохранить',exact:true}).click();
 const row=()=>page.locator('.domain-row').filter({hasText:'solo.example.test'});
 await row().waitFor();await row().getByRole('combobox').selectOption('2');
 await page.waitForResponse(r=>r.url().endsWith('/api/catalog')&&r.request().method()==='GET');
 assert.equal((await read()).standalone.find(d=>d.domain==='solo.example.test').slot,2);
 await row().getByRole('button',{name:'Удалить solo.example.test'}).click();await page.locator('#confirmOk').click();await row().waitFor({state:'detached'});
 await page.getByRole('button',{name:'+ Создать группу',exact:true}).click();
 await page.locator('#groupName').fill('Telegram');
 await page.locator('#editDomains').fill('91.108.56.0/22\n149.154.160.0/20');
 await page.locator('#editForm').getByRole('button',{name:'Сохранить',exact:true}).click();
 await page.getByRole('heading',{name:'Telegram',exact:true}).waitFor();
 assert.deepEqual((await read()).groups.find(g=>g.name==='Telegram').domains,['149.154.160.0/20','91.108.56.0/22']);
 await page.getByRole('button',{name:'+ Создать группу',exact:true}).click();
 await page.locator('#groupName').fill('Конфликт');await page.locator('#editDomains').fill('youtube.com');
 await page.locator('#editForm').getByRole('button',{name:'Сохранить',exact:true}).click();await page.locator('#editError').getByText(/уже принадлежит/).waitFor();
 assert.equal(await page.locator('#editor').isVisible(),true);
 await page.locator('#editor').getByRole('button',{name:'Отмена',exact:true}).click();
 const [download]=await Promise.all([page.waitForEvent('download'),page.locator('#diagnostics').click()]);
 assert.equal(download.suggestedFilename(),'pivas-diag.txt');
 await page.setViewportSize({width:1440,height:1100});await page.emulateMedia({colorScheme:'light'});
 assert.deepEqual(errors,[]);console.log('Browser PASS: explanation, load comparison, encrypted backup download/preview/restore, wrong password; one-click slot swap/back, preserved groups, swap error; device discovery, exclude/include, persistence, isolated other device, device search; mobile overflow, light/dark, create 8 domains, move group, disable/enable, edit, search, delete, individual add/move/delete, conflict, report download.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
