name: Предложение
description: Улучшение Pivas
title: "[Идея] "
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Какую задачу нужно решить?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Предлагаемое поведение
    validations:
      required: true
